spring:    
  datasource:
    url: jdbc:mysql://localhost:3306/zoologico
    username: root
    password: ""
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 30
          lob:
            non_contextual_creation: true

server:
  port: 8084
  servlet:
    context-path: /zoologico
